{ pkgs, ... }:

let
  myEmacs = pkgs.emacs;
  emacsWithPackages = (pkgs.emacsPackagesFor myEmacs).emacsWithPackages;
in emacsWithPackages (epkgs:
  (with epkgs.melpaPackages; [
    ace-window
    bats-mode
    blacken
    cape
    # ccls
    cython-mode
    deft
    direnv
    dumb-jump
    ebib
    elfeed
    elfeed-org
    elisp-def
    elisp-demos
    elpy
    emr
    ess
    ess-R-data-view
    eyebrowse
    flyspell-correct
    forge
    format-all
    gcmh
    general
    git-gutter
    git-gutter-fringe
    gnuplot-mode
    helpful
    highlight-defined
    highlight-function-calls
    highlight-indent-guides
    hl-todo
    iedit
    link-hint
    lispy
    lispyville
    magit
    magit-todos
    marginalia
    markdown-mode
    nix-mode
    no-littering
    orderless
    pdf-tools
    poetry
    matlab-mode
    prescient
    py-isort
    python-pytest
    rainbow-delimiters
    reformatter
    sly
    smartparens
    transient
    vlf
    which-key
    wiki-summary
    wordnut
    yasnippet
    yatemplate
  ]) ++ (with epkgs.elpaPackages; [ modus-themes vertico vundo popper jinx ])

  ++ (with epkgs; [
    citar
    citar-embark
    citar-org-roam
    citeproc
    consult
    consult-flycheck
    corfu
    cypher-mode
    dired-narrow
    dirvish
    elpher
    flycheck
    nov
    projectile
    edit-indirect
    avy
    embark
    embark-consult
    ement
    engrave-faces
    evil
    evil-args
    evil-collection
    evil-easymotion
    evil-exchange
    evil-goggles
    evil-lion
    evil-nerd-commenter
    evil-org
    evil-smartparens
    evil-surround
    evil-textobj-tree-sitter
    flymake-proselint
    git-timemachine
    mermaid-mode
    ob-async
    ob-mermaid
    org
    org-appear
    org-cliplink
    org-contrib
    org-modern
    sdcv
    orgit
    orgit-forge
    org-ref
    org-roam
    org-roam-bibtex
    org-roam-ui
    org-superstar
    ox-clip
    ox-hugo
    ox-pandoc
    ox-reveal
    poly-markdown
    saveplace-pdf-view
    tempel
    toml-mode
    tree-sitter-indent
    treesit-auto
    undo-fu
    undo-fu-session
    use-package
    visual-fill-column
    yaml-mode
    wgrep

    tree-sitter-ess-r
    treesit-grammars.with-all-grammars
  ]))
