# Function for setting up the host for a nixos container based service and
# setting some container defaults.
#
# It creates a host and container user that have the same uid and creates a
# host nginx virtual host to access the container's private network.
#
# To simplify calling this function it takes in a set then handles defaults
# manually.
# The required arguments are:
#   name: the name of the service (and the file under "./modules/service").
#   id: a unique id for the given service. Used to generate the container's ip
# Addresses and the user's uid;
#
# Optional arguments:
#   subdomain: the subdomain the webpage should be reached by (defaults to
# name). This is also used for naming the host side of things. This allows
# multiple instances of the same service to have seperate data/user/etc on the
# host side without impacting what the service inside the container sees.
# (container side uses name for all naming)
#
#   tld: "top level domain" (really just the domain). Defaults to home for now
# since thats what I'm using. By exposing this I can use a different domain
# to access test instances. In reality this should be a configuration option
# somewhere else that this reads.
#
#   ipAddress: an ip address that overrides the local address generated by the
# id. This is useful for containers that do not create their own private
# network. (i.e. it seemed much easier to just have adguard on the host network
# instead of setting up port 53 forwarding).

set:
{ config, ... }:
let
  values = rec {
    uid = set.id + 10000;
    hostAddress = "10.0.3.${(builtins.toString set.id)}";
    localAddress = "10.0.4.${(builtins.toString set.id)}";
    nameserver = if builtins.hasAttr "nameserver" set then
      set.nameserver
    else
      "192.168.0.101";
    ipAddress = localAddress;
    tld = "home";
    port = 3000;
    subdomain = set.name;
    extraConfig = if builtins.hasAttr "allowedIps" set then
      builtins.concatStringsSep "\n" (builtins.concatLists [
        (map (ip: "allow ${ip};") set.allowedIps)
        [ "deny all;" ]
      ])
    else
      "";
    users = {
      users."${set.name}" = {
        isSystemUser = true;
        home = "/var/lib/${set.name}";
        uid = uid;
        group = set.name;
      };
      groups."${set.name}" = { gid = uid; };
    };
    environment.etc."resolv.conf".text = "nameserver ${nameserver}";
  } // set;
  callPackage = f: values:
    f (builtins.intersectAttrs (builtins.functionArgs f) values);

  setup = { ipAddress, uid, tld, subdomain, port, extraConfig }: {
    services.nginx.virtualHosts."${subdomain}.${tld}".locations."/" = {
      inherit extraConfig;
      proxyPass = "http://${ipAddress}:${(builtins.toString port)}";
    };

    users = {
      users."${subdomain}" = {
        isSystemUser = true;
        home = "/data/${subdomain}";
        uid = uid;
        group = subdomain;
      };
      groups."${subdomain}" = { gid = uid; };
    };
  };

  service = import (../modules/services + "/${values.name}" + ".nix");
in (callPackage setup values) // (callPackage service values)
